env:
  ENVIRONMENT: development

http:
  address: 127.0.0.1:8080

  # max POST request size, including file uploads in MB.
  maxRequestSize: 200

  uploads:
    # list of file extensions which are forbidden for uploading.
    forbid: [".php", ".exe", ".bat"]

  # http worker pool configuration.
  workers:
    command: "php worker.php"
    relay: "pipes"
    pool:
      numWorkers: 1
      # maxJobs: 1 == reload worker after each request, 0 == unlimited (production value)
      maxJobs: 1
      destroyTimeout: 60
      allocateTimeout: 60

# Additional HTTP headers and CORS control.
headers:
  cors:
    allowedOrigin: "*"
    allowedHeaders: "*"
    allowedMethods: "GET,POST,PUT,DELETE"
    allowCredentials: true
    exposedHeaders: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
    maxAge: 600

  # Automatically add headers to every response.
  response:
    "X-Powered-By": "PHP/3"

static:
  dir: "public"
  forbid: [".php", ".htaccess"]
